# Generated by Django 5.1 on 2024-08-18 03:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_rename_product_orderitems_products_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderitems',
            name='products',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.product'),
        ),
    ]
