# Generated by Django 5.1 on 2024-08-18 04:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_customeraddress'),
    ]

    operations = [
        migrations.RenameField(
            model_name='customeraddress',
            old_name='Customer',
            new_name='customer',
        ),
        migrations.AddField(
            model_name='customeraddress',
            name='default_address',
            field=models.BooleanField(default=False),
        ),
    ]
